#!/usr/bin/env bash

# Matrix like display

function cleanup(){
    2>/dev/null exit 0
}

function binary_check(){
    hash lolcat 2>/dev/null || (>&2 echo "Command \"lolcat\" not found...please install it" && exit 1)
}

TEXT="$1"
if [[ -z "$1" ]]; then
    TEXT="hello world!"
fi

# Determine terminal width
TERM_WIDTH=$(tput cols)
REPS=$((TERM_WIDTH / ${#TEXT}))
REPS_TEXT=""

for (( i=0; i<REPS; i++ )); do 
    REPS_TEXT="${REPS_TEXT}\t${TEXT}"
done

while :; do    
    2>/dev/null echo -e "$REPS_TEXT" | sed 's/./&\n/g' | lolcat
done

trap 'cleanup' INT
